site_name: Birthdays
site_description: 'Provides a report on upcoming birthdays and an API for sending birthday greetings via e-mail.'
site_author: 'SYSTOPIA'
repo_url: https://github.com/systopia/de.systopia.birthdays

theme:
    name: material

nav:
    - 'Introduction': index.md
    - 'Report': report.md
    - 'Birthday mailings': birthday_mailings.md
    - 'Localisation': localisation.md

markdown_extensions:
    - attr_list
    - admonition
    - def_list
    - codehilite
    - toc:
          permalink: True
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.mark

plugins:
    - search:
          lang: en
